config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  resources :articles do
    resources :comments
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  root 'static_pages#home'
  
  get '/about', to: 'static_pages#about'
  get '/submit', to: 'articles#new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/article.rb
class Article < ApplicationRecord
   belongs_to :user
    has_many :comments
    validates :title, presence: true, length: { maximum: 50 }
    validates :post, presence: true
    validate :picture_size
    
    mount_uploader :picture, PictureUploader
    default_scope -> { order(created_at: :desc) } 
    
    private 
    
    # Validates the size of an uploaded picture.
    def picture_size
        if picture.size > 5.megabytes
            errors.add(:picture, "should be less than 5MB")
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article Created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  
    
    # @article = Article.new(article_params)

    # respond_to do |format|
    #   if @article.save
    #     format.html { redirect_to @article, notice: 'Article was successfully created.' }
    #     format.json { render :show, status: :created, location: @article }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @article.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def article_params
      params.require(:article).permit(:content)
    end
    
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :post, :user_id)
    end
    
  # confirms a logged-in user.
  def logged_in_user
    unless logged_in?
    flash[:danger] = "Please log in to be able to submit"
    redirect_to login_url
    end
  end
  
  def correct_user
    @user = current_user
    redirect_to(root_url) unless @user == current_user
  end
  
  def set_page
    @page = params[:page].to_i || 0
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<li id="article-<%= article.id %>">
  <%= link_to gravatar_for(article.user, size: 50), article.user %>
  <span class="user"><%= link_to article.user.username, article.user %></span>
  <span class="content"><%= article.title %></span>
  <span class="content"><%= article.post %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(article.created_at) %> ago.
  </span>
</li>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>
  <!--<span class="picture">-->
  <!--%= form.file_field :picture, accept: 'image/jpeq,image/gif,image/png' %>-->
  <!--</span>-->
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $('#article_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/articles/detail.html.erb
<p><%= @article.title %></p>
<p><%= @article.post %></p>
<p><%= @article.title %></p>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.post %></td>
        <td><%= article.user_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<% provide(:title, "Submit Article") %>
<head>
    <title><%= yield(:title) %> |</title>
</head>

<h1>Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>

<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
  <%= f.label :username %> <br />
  <%= f.text_field :commenter %>
</p>
<p>
  <%= f.label :Comment %> <br />
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>